### ISSUE TITLE
Small restyling suggest

### ISSUE THREAD

**Issue by yoyurec** [Endle/fireSeqSearch#53]
![image](https://user-images.githubusercontent.com/137919/200820971-9290af25-4ad2-44fd-8acd-7a78a85222fc.png)

```css
        #fireSeqSearchDom {
            margin: 0 1em;
        }
        #fireSeqSearchDom ul {
            margin: 0;
            padding: 0.6em;
            border: 1px dotted  gray;
            list-style: none;
        }
        #fireSeqSearchDom ul li + li {
            margin-top: 0.4em;
        }
        #fireSeqSearchDom ul li a {
            font-weight: bold;
            font-size: 15px;
        }
        #fireSeqSearchDom ul li a::before {
            content: ' ';
            display: inline-block;
            margin-right: 0.2em;
            line-height: 1em;
            width: 1em;
            height: 1em;
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' stroke-width='1.5' stroke='currentColor' fill='none' stroke-linecap='round' stroke-linejoin='round' viewBox='0 0 24 24'%3e%3cpath d='M0 0h24v24H0z' stroke='none'/%3e%3cpath d='M14 3v4a1 1 0 0 0 1 1h4'/%3e%3cpath d='M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2zM9 9h1m-1 4h6m-6 4h6'/%3e%3c/svg%3e");
            background-repeat: no-repeat;
            transform: translateY(2px);
        }
        .fireSeqSearchHitSummary {
            font-size: 0.9em
        }
        .fireSeqSearchHitSummary::before {
            content: "\00A0::\00A0";
        }
        .fireSeqSearchHighlight {
            padding: 0 4px;
            color: black !important;
            background-color: gold;
            border-radius: 3px;
        }
```
